node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('dockerbuild') {
     echo "Docker build"
    //  def app = docker.build("yanivomc/docker-nodejs-demo:${commit_id}", '.')

   }
   stage('sonarqube tests') {
     echo "Sonarqube"
    //   def app = docker.build("yanivomc/sonar:${commit_id}", '-f sonarbuild' , '.')

   }
   stage('docker build/push') {
     echo "Docker push"
    //  docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
    //    def app = docker.build("yanivomc/docker-nodejs-demo:${commit_id}", '.').push()
    //  }
   }
}
